easy_admin:
    site_name: 'Trash Project'
    entities:
        - App\Entity\Carte
        - App\Entity\Cases
        - App\Entity\Forum
        - App\Entity\User
        - App\Entity\Logs
        - App\Entity\Chat
        - App\Entity\Partie
        - App\Entity\Jouer
    
